---
- name: Add docker key
  # TODO: wait for https://github.com/ansible/ansible/pull/5589 to merge
  # apt_key: id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
  apt_key: "url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present"

- name: Add docker repository
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
  notify:
    - Add docker repository

- name: Add docker
  apt: pkg=lxc-docker state=present

- name: Add some pre-requisite packages
  apt: "pkg={{item}} state=present"
  with_items:
    - python-pycurl
    - python-pip

- name: Install docker-py
  pip: name=docker-py state=present

- name: Run docker hello world
  docker: command='/bin/echo hello world' image=ubuntu detach=False
